finances/urls.py
from django.urls import path

from .views import (
    index,
    transacoes_por_usuario,
    contas_por_usuario,
    nova_conta,
    nova_transacao,
    detalhe_conta,
    perfil_usuario,
    editar_conta,
    criar_usuario
)

app_name = "finances"

urlpatterns = [
    path("", index, name="index"),
    path(
        "transactions/",
        transacoes_por_usuario,
        name="transacoes_por_usuario"
    ),
    path(
        "accounts/",
        contas_por_usuario,
        name="contas_por_usuario"
    ),
    path(
        "accounts/new/",
        nova_conta,
        name="nova_conta"
    ),
    path(
        "transactions/new/",
        nova_transacao,
        name="nova_transacao"
    ),
    path(
        "accounts/<int:conta_id>/",
        detalhe_conta,
        name="detalhe_conta"
    ),
    path(
        "perfil/",
        perfil_usuario,
        name="perfil_usuario"
    ),
    path(
        "accounts/<int:conta_id>/editar",
        editar_conta,
        name="editar_conta"
    ),
    path(
        "criar-usuario/",
        criar_usuario,
        name="criar_usuario"
    )
]

personal_finances/urls.py
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('finances/', include('finances.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/finances/'))
]

finances/models.py
from django.db import models
from django.contrib.auth.models import User


class ContaFinanceira(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    nome = models.CharField(max_length=100, null=False)
    saldo = models.FloatField(default=0)
    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'tb_contas_financeiras'


class Transacao(models.Model):
    # Quando temos chaves estrangeiras em uma model que referenciam
    # o mesmo campo na model relacionada, precisamos informar o argumento
    # 'related_name', pois senão, o Django não consegue diferenciar
    # os campos.
    conta_debito = models.ForeignKey(
        ContaFinanceira, models.CASCADE, related_name='conta_debito'
    )

    conta_credito = models.ForeignKey(
        ContaFinanceira, models.CASCADE, related_name='conta_credito'
    )

    valor = models.FloatField()

    criado_em = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'tb_transacoes'

finances/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.db.models import Q
from django.contrib.auth.models import User


from .models import Transacao, ContaFinanceira


@login_required
def index(request):

    return render(
        request, "finances/index.html")


@login_required
def transacoes_por_usuario(request):
    todas_transacoes = Transacao.objects.filter(
        conta_debito__usuario=request.user
    )

    context = {
        "todas_transacoes": todas_transacoes
    }

    return render(
        request,
        "finances/transacoes_por_usuario.html",
        context
    )


@login_required
def contas_por_usuario(request):
    todas_contas = ContaFinanceira.objects.filter(
        usuario=request.user
    )

    context = {
        "todas_contas": todas_contas
    }

    return render(
        request,
        "finances/contas_por_usuario.html",
        context
    )


@login_required
def nova_conta(request):
    if request.method == "GET":
        return render(request, "finances/nova_conta.html")

    elif request.method == "POST":
        nome_nova_conta = request.POST.get("nome_conta")

        nova_conta = ContaFinanceira(
            usuario=request.user,
            nome=nome_nova_conta
        )
        nova_conta.save()

        return HttpResponseRedirect(
            reverse("finances:contas_por_usuario", )
        )


@login_required
def nova_transacao(request):
    contas_do_usuario = ContaFinanceira.objects.filter(
        usuario=request.user
    )

    if request.method == "GET":

        context = {
            "contas_do_usuario": contas_do_usuario
        }

        return render(
            request,
            "finances/nova_transacao.html",
            context
        )

    elif request.method == "POST":

        conta_debitada_id = int(request.POST.get("conta_debitada_id"))
        conta_creditada_id = int(request.POST.get("conta_creditada_id"))

        if conta_debitada_id == conta_creditada_id:
            context = {
                "erro": "Você não pode definir a mesma conta como débito e crédito",
                "contas_do_usuario": contas_do_usuario
            }

            return render(request, "finances/nova_transacao.html", context)

        valor_transacao = request.POST.get("valor_transacao")
        valor_transacao = valor_transacao.replace(",", ".")
        valor_transacao = float(valor_transacao)

        conta_debitada = ContaFinanceira.objects.get(pk=conta_debitada_id)
        conta_creditada = ContaFinanceira.objects.get(pk=conta_creditada_id)

        conta_debitada.saldo -= valor_transacao
        conta_creditada.saldo += valor_transacao

        transacao = Transacao(
            conta_debito=conta_debitada,
            conta_credito=conta_creditada,
            valor=valor_transacao
        )

        transacao.save()
        conta_debitada.save()
        conta_creditada.save()

        return HttpResponseRedirect(
            reverse("finances:transacoes_por_usuario", )
        )


@login_required
def detalhe_conta(request, conta_id):
    conta = ContaFinanceira.objects.get(pk=conta_id)

    if conta.usuario != request.user:
        return HttpResponse("Você não tem acesso a essa página", status=401)

    transacoes = Transacao.objects.filter(
        Q(conta_debito=conta) | Q(conta_credito=conta)
    )

    context = {
        "conta": conta,
        "transacoes": transacoes
    }

    return render(
        request,
        "finances/detalhe_conta.html",
        context
    )

@login_required
def perfil_usuario(request):
    num_transacoes = Transacao.objects.filter(
        conta_debito__usuario=request.user
    ).count()

    num_contas = ContaFinanceira.objects.filter(
        usuario=request.user
    ).count()

    context = {
        "num_transacoes": num_transacoes,
        "num_contas": num_contas
    }

    return render(
        request, "finances/perfil_usuario.html", context)

@login_required
def editar_conta(request, conta_id):

    conta = get_object_or_404(ContaFinanceira, pk=conta_id)

    if request.method == "GET":
        return render(request, "finances/editar_conta.html", {"conta": conta})

    elif request.method == "POST":

        nome_conta = request.POST.get("nome_conta", conta.nome)
        conta.nome = nome_conta
        conta.save()

        return HttpResponseRedirect(reverse("finances:detalhe_conta", args=(conta.id,)))

def criar_usuario(request):
    if request.method == "GET":
        return render(request, "finances/criar_usuario.html")

    elif request.method == "POST":
        username = request.POST.get("username")
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        email = request.POST.get("email")
        password = request.POST.get("password")

        User.objects.create_user(
            username=username, 
            first_name=first_name, 
            last_name=last_name, 
            email=email, 
            password=password
        )


        return HttpResponseRedirect(
            reverse("login")
        )

finances/templates/finances/contas_por_usuario.html
{% extends 'template_base.html' %}

{% block content %}
    <div class="row">
        <div class="col d-flex justify-content-center">
            <h3>Contas de {{ user.username }}</h3>
        </div>
    </div>
    <hr>

    <div class="row">
        <div class="col d-flex justify-content-center">
            <a href="{% url 'finances:nova_conta' %}">Criar nova conta</a>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-6">
            <table class="table table-sm table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Nome da conta</th>
                        <th>Saldo</th>
                    </tr>
                </thead>
                <tbody>
                    {% for conta in todas_contas %}
                    <tr>
                        <td><a href="{% url 'finances:detalhe_conta' conta.id %}">{{ conta.nome }}</a></td>
                        <td>{{ conta.saldo }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

finances/templates/finances/criar_usuario.html
{% extends 'template_base.html' %}

{% block content %}
 <div class="row justify-content-center">
    <div class="col col-6">
        <h1>Criar novo usuário</h1>
        <hr>
    </div>
 </div>

<form action="" method="post">
    {% csrf_token %} 
    
    <div class="row justify-content-center">
        <div class="col col-6">
    <div class="row">
        <div class="col">
            <label for="username" class="form-label">Nome de Usuário</label>
            <input type="text" name="username" id="username" class="form-control">
        </div>
    </div>

    <div class="row">
        <div class="col">
            <label for="first_name" class="form-label">Primeiro Nome</label>
            <input type="first_name" name="first_name" id="first_name" class="form-control">
        </div>
    </div>

    <div class="row">
        <div class="col">
            <label for="last_name" class="form-label">Sobrenome</label>
            <input type="last_name" name="last_name" id="last_name" class="form-control">
        </div>
    </div>

    <div class="row">
        <div class="col">
            <label for="email" class="form-label">E-mail</label>
            <input type="email" name="email" id="email" class="form-control">
        </div>
    </div>

    <div class="row">
        <div class="col">
            <label for="password" class="form-label">Senha</label>
            <input type="password" name="password" id="password" class="form-control">
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col">
            <button class="btn btn-success w-100">Cadastrar</button>
        </div>
    </div>
</div>
</form>
    
    
{% endblock %}

finances/templates/finances/detalhe_conta.html
{% extends 'template_base.html' %}

{% block content %}

    <div class="row">
        <div class="col d-flex justify-content-center">
            <h3>Detalhes da conta '{{ conta.nome }}'</h3>
        </div>
    </div>
    <hr>

    <div class="row">
        <div class="col">
            Saldo: R$ {{ conta.saldo }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            Data de criação: {{ conta.criado_em|date:"d/m/Y" }}
        </div>
    </div>
    <div class="row mb-3">
        <div class="col">
            Última atualização: {{ conta.atualizado_em|date:"d/m/Y" }}
        </div>
    </div>
    
    <div class="row">
        <div class="col">
            <a href="{% url 'finances:editar_conta' conta.id %}">Editar contas</a>
        </div>
    </div>

    <div class="row">
        <div class="col d-flex justify-content-center">
            <h4>Transações com {{ conta.nome }}</h4>
        </div>
    </div>
    <hr>

{% if transacoes %}
    <div class="row justify-content-center">
        <div class="col col-6">
            <table class="table table-sm table-striped">
                <thead>
                    <tr>
                        <th>Conta Debitada</th>
                        <th>Conta Creditada</th>
                        <th>Valor da Transação</th>
                        <th>Data/Hora</th>
                    </tr>
                </thead>
                <tbody>
                {% for transacao in transacoes %}
                    <tr>
                        <td>{{ transacao.conta_debito.nome }}</td>
                        <td>{{ transacao.conta_credito.nome }}</td>
                        <td>R$ {{ transacao.valor }}</td>
                        <td>{{ transacao.criado_em|date:"d/m/Y" }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% else %}
    <p>Essa conta não aparece em nenhuma transação</p>
{% endif %}

{% endblock %}

finances/templates/finances/editar_conta.html
{% extends 'template_base.html' %} 

{% block content %}

<form action="" method="post">
{% csrf_token %}
<div class="row justify-content-center">
  <div class="col col-3 mb-2">
      <label for="nome_conta" class="form-label">Nome da conta:</label>
      <input type="text" name="nome_conta" id="nome_conta" class="form-control" value="{{conta.nome}}"/>
    </div>
</div>
<div class="row">
    <div class="col d-flex justify-content-center">
        <button class="btn btn-primary">Enviar</button>
    </div>
</div>
</form>

{% endblock %}

finances/templates/finances/index.html
{% extends 'template_base.html' %}

{% block content %}

 <!--Ícone da página-->
    <div class="row">
        <div class="col d-flex justify-content-center">
            <h1>Finanças Pessoais</h1>
        </div>
    </div>
    <hr>

    
{% endblock content %}

finances/templates/finances/nova_conta.html
{% extends 'template_base.html' %}

{% block content %}
  <h1>Criar nova conta</h1>
  <hr>

  <form action="" method="post">
    {% csrf_token %}
    <label for="txtNomeConta">Nome da Conta:</label>
    <input type="text" name="nome_conta" id="txtNomeConta">
    <input type="submit" value="Cadastrar">
  </form>

  <br><br>

  <a href="{% url 'finances:contas_por_usuario' %}">Voltar para a listagem de contas</a><br>
  <a href="{% url 'finances:index' %}">Voltar para a página principal</a>
{% endblock %}

finances/templates/finances/nova_transacao.html
{% extends 'template_base.html' %}

{% block content %}
  <h1>Criar nova transação</h1>
  <hr>

  {% if erro %}
    <strong>{{ erro }}</strong>
  {% endif %}

  <form action="" method="post">
    {% csrf_token %}
    <table style="border-style: double; border-color: white">
      <tr>
        <th>Conta a ser debitada</th>
        <th>Conta a ser creditada</th>
        <th>Valor da transação</th>
      </tr>
      <tr>
        <td>
          <select name="conta_debitada_id">
            {% for conta in contas_do_usuario %}
              <option value="{{ conta.id }}">{{ conta.nome }}</option>
            {% endfor %}
          </select>
        </td>
          <td>
          <select name="conta_creditada_id">
            {% for conta in contas_do_usuario %}
              <option value="{{ conta.id }}">{{ conta.nome }}</option>
            {% endfor %}
          </select>
          </td>
          <td>
              <input type="text" name="valor_transacao">
          </td>
      </tr>
    </table>
      <br>
      <div class="col col-3 d-flex justify-content-end">
        <input type="submit" value="Cadastrar Transação" class="btn btn-success btn-sm">
      </div>
    </form>
{% endblock %}

finances/templates/finances/perfil_usuario.html
{% extends 'template_base.html' %}

{% block content %}
    <div class="row">
        <div class="col">
            <h1>Perfil de {{ user.username }}</h1>
            <hr>
        </div>
    </div>

    <div class="row justify-content-start">
        <div class="col col-2">
            Nome
        </div>
        <div class="col col-3">
            <strong>{{ user.first_name }} {{ user.last_name }}</strong>
        </div>
    </div>
    <div class="row justify-content-start">
        <div class="col col-2">
            E-mail
        </div>
        <div class="col col-3">
            <i>{{ user.email }}</i>
        </div>
    </div>

    <div class="row justify content start">
        <div class="col col-2">
            Cadastrado em:
        </div>
        <div class="col col-3">
            {{ user.date_joined|date:"d/m/Y H:i:s" }}
        </div>
    </div>

    <div class="row justify-content-start">
        <div class="col col-2">
            Último login:
        </div>
        <div class="col col-3">
            {{ user.last_login| date:"d/m/Y H:i:s" }}
        </div>
    </div>

    <div class="row justify-content-start">
        <div class="col col-2">
            Número de contas
        </div>
        <div class="col col-3">
            <strong><a href="{% url 'finances:contas_por_usuario' %}">{{ num_contas }}</a></strong>
        </div>
    </div>

    <div class="row justify-content-start">
        <div class="col col-2">
            Número de transações
        </div>
        <div class="col col-3">
            <strong><a href="{% url 'finances:transacoes_por_usuario' %}">{{ num_transacoes }}</a></strong>
        </div>
    </div>

{% endblock %}

finances/templates/finances/transacoes_por_usuario.html
{% extends 'template_base.html' %}

{% block content %}
    <div class="row">
        <div class="col d-flex justify-content-center">
            <h3>Transações de {{ user.username }}</h3>
        </div>
    </div>
    <hr>
        
    <div class="row mb-3">
        <div class="col d-flex justify-content-center">
            <a href="{% url 'finances:nova_transacao' %}">Criar nova transação</a>    
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col">
            <table class="table table-sm table-striped table-bordered">
                <tr>
                    <th>Conta debitada</th>
                    <th>Conta Creditada</th>
                    <th>Valor da transação</th>
                    <th>Data/Hora</th>
                </tr>
                {% for transacao in todas_transacoes %}
                    <tr>
                        <td><a href="{% url 'finances:detalhe_conta' transacao.conta_debito.id %}">{{ transacao.conta_debito.nome }}</a></td>
                        <td><a href="{% url 'finances:detalhe_conta' transacao.conta_credito.id %}">{{ transacao.conta_credito.nome }}</a></td>
                        <td>R$ {{ transacao.valor }}</td>
                        <td>{{ transacao.criado_em|date:"d/m/Y" }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>

{% endblock %}

templates/template_base.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    

    <!-- Bootstrap CSS -->
    <!-- https://cdnjs.com/libraries/twitter-bootstrap/5.0.0-beta1 -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-beta1/css/bootstrap.min.css"
    />

    <!-- Icons: https://getbootstrap.com/docs/5.0/extend/icons/ -->
    <!-- https://cdnjs.com/libraries/font-awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
    />
    <!-- Animation text -->
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
    />
  <style>
    *{
      color: white;
      overflow: hidden;
    }
    body {
      background-color: #FF3CAC;
      background-image: linear-gradient(225deg, #FF3CAC 0%, #784BA0 50%, #2B86C5 100%);
      background-size: 400% 400%;
      animation: gradient 10s ease infinite;
      height: 100vh; 
    }
    @keyframes gradient {
      0% {
        background-position: 0% 50%;
      }
      50% {
        background-position: 100% 50%;
      }
      100% {
        background-position: 0% 50%;
      }
    }
    input{
      color: black;
    }
    a.nav-link{
      color: #5726e3;
    }
    a{
      color: skyblue;
    }
    select, option{
      color: black;
    }
    h2{
      filter: drop-shadow(5px 5px 4px #FFFFFF);
      animation: animated_text 2s ease-in-out infinite;
      color: white;
    }
    @keyframes pulse {
      0% {
      -webkit-transform: scaleX(1);
      transform: scaleX(1);
      }
      50% {
      -webkit-transform: scale3d(1.05,1.05,1.05);
      transform: scale3d(1.05,1.05,1.05);
      }
      100% {
      -webkit-transform: scaleX(1);
      transform: scaleX(1);
      }
    }
  </style>
  
    <title>Personal Finances</title>
  </head>
  <body>

    {% if user.is_authenticated %}
        <header>
            <div class="navbar navbar-expand-md bg-light">
                <div class="container-fluid">
                    <a href="#" class="navbar-brand"></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav mx-auto">
                            <li class="nav-item">
                                <a href="{% url 'finances:index' %}" class="nav-link" active aria-current="page">Página Principal</a>
                            </li>
                            <div class="nav-item">
                                <a href="{% url 'finances:contas_por_usuario' %}" class="nav-link">Contas</a>
                            </div>
                            <div class="nav-item">
                                <a href="{% url 'finances:transacoes_por_usuario' %}" class="nav-link">Transações</a>
                            </div>
                            <div class="nav-item">
                                <a href="{% url 'finances:perfil_usuario' %}" class="nav-link">Perfil</a>
                            </div>
                            <div class="nav-item">
                                <a href="{% url 'logout' %}" class="nav-link">Sair</a>
                            </div>
                        </ul>
                    </div>
                </div>
            </div>
        </header>
    {% endif %}

    <div class="container">
        <main>
            {% block content %}{% endblock content %}
        </main>
    </div>
    <br>
    <footer>
      <h2 class="animate__animated animate__pulse" align="center"></h2>
      <script>
        const currentTime = () => {
            const el = document.querySelector("h2");
    
            let date = new Date();
            let hh = date.getHours();
            let mm = date.getMinutes();
            let ss = date.getSeconds();
    
            hh = hh < 10 ? `0${hh}` : hh;
            mm = mm < 10 ? `0${mm}` : mm;
            ss = ss < 10 ? `0${ss}` : ss;
            
            let time = `${hh}:${mm}:${ss}`;
            el.innerText = time;
        }
    
        currentTime();
        setInterval(currentTime, 1000);
    </script>
    </footer>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-beta1/js/bootstrap.bundle.min.js"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->

    <!-- https://cdnjs.com/libraries/popper.js/2.5.4 -->
    <!-- <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.5.4/umd/popper.min.js"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-beta1/js/bootstrap.min.js"
    ></script> -->

    <!-- More: https://getbootstrap.com/docs/5.0/getting-started/introduction/ -->
  </body>
</html>